07-Sorting/C/selection_sort.c

Implementing the selection sort algorithm in C language.

feat: implementing selection sort in c language

---

07-Sorting/C/quicksort.c

Implementing the quick sort algorithm in C language.

feat: implementing quickSort in C language

---

07-Sorting/C/insertion_sort.c

Implementing the insertion sort algorithm in C language.

feat: implementing insertion sort in c language

---

07-Sorting/C/bubble_sort.c

Implementing the bubble sort algorithm in C language.

feat: implementing bubble sort in c language

---

07-Sorting/C/merge_sort.c

Implementing the merge sort algorithm in C language.

feat: implementing merge sort in C language

---

stack/mergw_two_stack.cpp

merge two stack

---

07-Sorting/merge_sort.java

Please merge this pull request asap!! Thanks :))

Merge Sort in Java is added!!

---

07-Sorting/C/heap_sort.c

Kindly merge this pull request asap !!

Program of Heap Sort in C language is added!!

---

Problems/Readers And Writers/main.c
Problems/Readers And Writers/makefile
Problems/Readers And Writers/resource_monitor.c
Problems/Readers And Writers/resource_monitor.h

Solving the problem of Readers and Writers in C language using monitor, mutex and threads.

Solving Readers and Writers Operational System Problem

---

LeetCode/2399. Check Distances Between Same Letters.cpp

Create 2399. Check Distances Between Same Letters.cpp

added code to leet code

---

LeetCode/Car pooling.cpp
LeetCode/Flower Planting With No Adjacent.cpp
LeetCode/Remove All Adjacent Duplicates In String.cpp
LeetCode/day of the year.cpp

Leetcode cpp questions

---

07-Sorting/Counting Sort.cpp

Create Counting Sort.cpp

---

LeetCode/First Letter to Appear Twice.cpp

First Letter to Appear Twice Solution

Create First Letter to Appear Twice.cpp

---

LeetCode/Valid Anagram.cpp

Create Valid Anagram.cpp

---

Recursion in DSA/Move_last_array.java

A new file named Move_last_array.java is added in the directory of Recursion in DSA.
please review and merge the pr.

A new file named Move_last_array.java is added 

---

LeetCode/509-FibonacciNumber.java

This is the only solution of Fibonacci no. which works in linear time complexity

Added 509- Fibonacci Number

---

Dynamic_Programming/DP_2D/MatrixChainMultiplication.java
Greedy/MinimumWalkingDistance.java

Iiitg git host

---

LeetCode/2397 - Maximum Rows Covered by Columns.cpp

2397 - Maximum Rows Covered by Columns.cpp

---

Recursion in DSA/generate_parenthesis.java

Hi anwesh,
I have added generate_parenthesis.java under the folder "Recursion in DSA", which contains code for the leetcode problem(22. Generate Parentheses).
Thank you.

added code for generate_parenthesis

---

Algorithms/Prim's_algorithm.c
Algorithms/kruskal's_algorithm.c

Added various algorithms for spanning tree like Prim's algorithm, Kruskal's algorithm in c.

Added various algorithms for spanning tree

---

LeetCode/LEETCODE First best version.java

Here is the solution of Leetcode's problem first bad version.

LEETCODE First best version.java

---

LeetCode/LEETCODE Median of two sorted arrays.java

Here is the solution of Leetcode's problem  Median of two sorted arrays.

 LEETCODE Median of two sorted arrays.java

---

Subarray.java

Here is the code to create subarrays using brute force as well as optimized logics.

Subarray.java

---

LeetCode/2367. Number of Arithmetic Triplets.cpp

Create 2367. Number of Arithmetic Triplets.cpp

---

LeetCode/350. Intersection of Two Arrays II.cpp

Create 350. Intersection of Two Arrays II.cpp

---

07-Sorting/heapsort.cpp

heapsort in c++

---

LeetCode/2239. Find Closest Number to Zero.cpp

Create 2239. Find Closest Number to Zero.cpp

---

LeetCode/2227. Encrypt and Decrypt Strings.cpp

Create 2227. Encrypt and Decrypt Strings.cpp

---

LeetCode/2242. Maximum Score of a Node Sequence.cpp

Create 2242. Maximum Score of a Node Sequence.cpp

---

LeetCode/2224. Minimum Number of Operations to Convert Time .cpp

Create 2224. Minimum Number of Operations to Convert Time .cpp

---

LeetCode/2259. Remove Digit From Number to Maximize Result.cpp

Create 2259. Remove Digit From Number to Maximize Result.cpp

---

LeetCode/2248. Intersection of Multiple Arrays.cpp

Create 2248. Intersection of Multiple Arrays.cpp

---

LeetCode/2124. Check if All A's Appears Before All B's.cpp

Create 2124. Check if All A's Appears Before All B's.cpp

---

LeetCode/121. Best Time to Buy and Sell Stock.cpp

Create 121. Best Time to Buy and Sell Stock.cpp
